system:
  http:
    host: '0.0.0.0'
    port: 8080
    read_timeout: 5
    write_timeout: 5
  grpc:
    port: 10000
  db:
    host: '192.168.0.108'
    port: 5432
    user: "mp_admin"
    password: "mp_admin"
    db_name: 'mind_palace'
    max_conn: 100
    timeout: 5
logger:
  level: trace